name = "wechat"
main = "src/index.ts"
compatibility_date = "2023-05-22"

kv_namespaces = [
  { binding = "KV", id = "2097a73a271e4ebda65d303915b5af65", preview_id = "2097a73a271e4ebda65d303915b5af65" }
]
